name: Download BT Link with Docker

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    container:
      image: linuxserver/transmission:latest # 使用 Transmission Docker 镜像
      volumes:
        - downloads:/downloads # 挂载卷，用于存储下载的文件

    steps:
      - name: Download BT link
        id: download_bt
        continue-on-error: true
        run: |
          BT_LINK="magnet:?xt=urn:btih:99ffbc44b8328390b9bbb7ef942ebcc042782b0e&dn=[www.domp4.cc]%E5%BC%82%E5%BD%A2%EF%BC%9A%E5%A4%BA%E5%91%BD%E8%88%B0.2024.BD1080p.%E5%9B%BD%E8%8B%B1%E5%8F%8C%E8%AF%AD.%E4%B8%AD%E8%8B%B1%E5%AD%97.mp4&tr=..."
          transmission-remote -a "$BT_LINK" -w /downloads || echo "::set-output name=download_failed::true"

      - name: List downloaded files
        if: steps.download_bt.outputs.download_failed != 'true'
        run: ls -l /downloads

      - name: Archive downloaded files
        if: steps.download_bt.outputs.download_failed != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: bt_downloads
          path: /downloads

     
