name: Test N_m3u8DL-CLI

on:
  workflow_dispatch:
    inputs:
      trailer_url:
        description: '请输入预告片链接'
        required: true
      best_video_m3u8:
        description: '请输入最佳质量视频的m3u8链接'
        required: false
      best_audio_m3u8:
        description: '请输入最佳音频的m3u8链接'
        required: false
      enable_download:
        description: '是否启用下载步骤'
        required: true
        type: choice
        options:
          - '关闭'
          - '启用'

jobs:
  test-m3u8dl-cli:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download N_m3u8DL-CLI
      run: |
        Invoke-WebRequest -Uri https://github.com/nilaoda/N_m3u8DL-CLI/releases/download/3.0.2/N_m3u8DL-CLI_v3.0.2.exe -OutFile N_m3u8DL-CLI.exe

    - name: Download ffmpeg
      run: |
        Invoke-WebRequest -Uri https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip -OutFile ffmpeg-latest.zip
        Expand-Archive -Path ffmpeg-latest.zip -DestinationPath ffmpeg
        Move-Item ffmpeg/*/bin/ffmpeg.exe .

    - name: Process input URL
      run: |
        $trailerUrl = "${{ github.event.inputs.trailer_url }}"
        $processedUrl = $trailerUrl -replace "amp;", ""
        echo $processedUrl > input.txt

    - name: Test N_m3u8DL-CLI
      run: |
        mkdir workdir
        .\N_m3u8DL-CLI.exe $(Get-Content input.txt) --enableParseOnly --workDir workdir
        dir workdir

    - name: Conditional download and merge
      if: ${{ github.event.inputs.enable_download == '启用' }}
      run: |
        $videoUrl = "${{ github.event.inputs.best_video_m3u8 }}"
        $audioUrl = "${{ github.event.inputs.best_audio_m3u8 }}"
        if ($videoUrl -ne "") {
          .\ffmpeg.exe -i $videoUrl -c copy video.mp4
        }
        if ($audioUrl -ne "") {
          .\ffmpeg.exe -i $audioUrl -c copy audio.mp4
        }
        if ($videoUrl -ne "" -and $audioUrl -ne "") {
          .\ffmpeg.exe -i video.mp4 -i audio.mp4 -c copy final_output.mp4
          Remove-Item video.mp4, audio.mp4
        }

    - name: Upload final output
      if: ${{ github.event.inputs.enable_download == '启用' }}
      run: |
        $videoUrl = "${{ github.event.inputs.best_video_m3u8 }}"
        $audioUrl = "${{ github.event.inputs.best_audio_m3u8 }}"
        if ($videoUrl -ne "" -and $audioUrl -ne "") {
          echo "Uploading final_output.mp4"
          mv final_output.mp4 output.mp4
        } elseif ($videoUrl -ne "") {
          echo "Uploading video.mp4"
          mv video.mp4 output.mp4
        } elseif ($audioUrl -ne "") {
          echo "Uploading audio.mp4"
          mv audio.mp4 output.mp4
        }

    - name: Upload output
      if: ${{ github.event.inputs.enable_download == '启用' }}
      uses: actions/upload-artifact@v4
      with:
        name: final_output
        path: output.mp4
